### ISSUE TITLE
person votes details: scroll should show more votes

### ISSUE THREAD

**Issue by yamila-moreno** [dont-worry-be-happy/dwbh-front#26]
currently, it seems to show past week, which means that the scroll shows from 1 to 5 new rows. Nonetheless these are little rows for a  quick scan.

Proposal: show the next 20 rows. I guess this also affects @mariogarcia regarding the filter of the API.

**Comment by bameda** [comment]
Fixed, increasing the page size. But the problem is that there is no call available to get the last n votes easily. I can only request them between two dates.
